### ISSUE TITLE
Test Case for Ques 2 missing

### ISSUE THREAD

**Issue by Erick2206** [DigiCred/upes-assignments#1]
Please provide a test case for question 2.

**Comment by namitajuneja** [comment]
Now available

**Comment by devershichandra27** [comment]
Share link?

**Comment by Erick2206** [comment]
@namitajuneja  where are the test cases?

**Comment by veris-amoghbanta** [comment]
Lets say,
- travelTimes = [3000, 5000],
- readyTimes = [0, 8000, 20000],
- cancelTimes = [2000, 10000, 30000]

So, the input will be something like : **[[3000, 5000], [0, 8000, 20000], [2000, 10000, 30000]]**
And the output should be an integer : **18000**

**Comment by ashishzone** [comment]
Sir,wont the output be 20000 for the above mentioned test cases?

**Comment by manankalra** [comment]
@veris-amoghbanta more test cases please? Question 2 seems vague.

**Comment by Erick2206** [comment]
@veris-amoghbanta shouldn't the answer be 20,000 because the readyTime of all rider is 20,000. How can the total trip time be less than readyTime of last rider?

**Comment by AadarshKumayan** [comment]
@veris-amoghbanta is it mandatory for the driver to service all the request in question 2

**Comment by aseemsharma40** [comment]
Sir , Can we get more test cases for question 2?
