### ISSUE TITLE
Plagarism check

### ISSUE THREAD

**Issue by chshbh** [DigiCred/upes-assignments#4]
how are you going to check plagarism? 
https://www.codechef.com/ACMAMR15/problems/AMR15B
https://www.codechef.com/JAN14/problems/MTRICK

**Comment by veris-amoghbanta** [comment]
Your comments and code documentation will be parameter 1.
We have other tools to check that too and finally we can always discuss your answers on a call.
Don't worry about it, just give your best 😄
