### ISSUE TITLE
Need extension

### ISSUE THREAD

**Issue by Erick2206** [DigiCred/upes-assignments#41]
@veris-amoghbanta , many of us are busy in placement process of LTI that is scheduled for today and tomorrow, so can we get time extension till wednesday 6 pm?

**Comment by aseemsharma40** [comment]
An extension would be really helpful if it is possible.

**Comment by veris-amoghbanta** [comment]
Lets make it Wednesday 8 A.M. Thats the best we can do.

**Comment by ashishzone** [comment]
@veris-amoghbanta please extend submission timming  till 11 am or so , we were  busy in our placement activities.
